symfony/src/Entity/Post.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post as Poster;
use App\Controller\PostUserController;
use App\Controller\UploadPostController;
use App\Repository\PostRepository;
use App\State\PostCollectionProvider;
use App\State\PostItemProvider;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ApiResource(
    operations: [
        new Get(
            uriTemplate: '/post_detail/{id}',
            requirements: ['id' => '\d+'],
            normalizationContext: ['groups' => 'post:item'],
            provider: PostItemProvider::class,
        ),
        new Get(
            normalizationContext: ['groups' => 'post:item'],
        ),
        new GetCollection(
            controller: PostUserController::class,
            normalizationContext: ['groups' => 'post:list'],
        ),
        new Poster(
            inputFormats: ['multipart' => ['multipart/form-data']],
            controller: UploadPostController::class,
            denormalizationContext: ['groups' => 'post:create'],
            deserialize: false
        ),
        new Delete()
    ],
    order: ['createdAt' => 'DESC'],
    paginationEnabled: true,
    paginationItemsPerPage: 20,
)]
//#[ApiFilter(SearchFilter::class, properties: ['likedPosts.user' => 'exact'])]
class Post
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['post:list', 'post:item', 'comment:list', 'post:create'])]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Groups(['post:list', 'post:item', 'post:create'])]
    private ?string $title = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank()]
    #[Groups(['post:list', 'post:item', 'post:create'])]
    private ?string $text = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank()]
    #[Groups(['post:list', 'post:item', 'post:create'])]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, cascade: ['persist', 'remove'])]
    #[Groups(['post:item'])]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: LikedPost::class, cascade: ['persist', 'remove'])]
    private Collection $likedPosts;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['post:list', 'post:item'])]
    private ?string $image = null;

    #[Groups(['post:create'])]
    #[SerializedName('file')]
    private ?UploadedFile $file = null;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->likedPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LikedPost>
     */
    public function getLikes(): Collection
    {
        return $this->likedPosts;
    }

    public function addLikedPost(LikedPost $likedPost): self
    {
        if (!$this->likedPosts->contains($likedPost)) {
            $this->likedPosts->add($likedPost);
            $likedPost->setPost($this);
        }

        return $this;
    }

    public function removeLikedPost(LikedPost $likedPost): self
    {
        if ($this->likedPosts->removeElement($likedPost)) {
            // set the owning side to null (unless already changed)
            if ($likedPost->getPost() === $this) {
                $likedPost->setPost(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getFile(): ?UploadedFile
    {
        return $this->file;
    }

    public function setFile(?UploadedFile $file): void
    {
        $this->file = $file;
    }



    #[Groups(['post:list', 'post:item'])]
    #[SerializedName('createdAt')]
    public function getCreatedAtTimestampable(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }
}

symfony/src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
                'attr' => array(
                    'placeholder' => 'Votre titre...'
                ),
                'row_attr' => [
                    'class' => 'flex flex-col m-4 w-4/5'
                ]
                ])
            ->add('text', TextareaType::class, [
                'label' => 'Contenu du post',
                'attr' => array(
                    'rows' => 8,
                    'cols' => 30,
                    'placeholder' => 'Contenu de votre post...'
                ),
                'row_attr' => [
                    'class' => 'flex flex-col m-4 w-4/5'
                ]
            ])
            ->add('imageFile', FileType::class, [
                'label' => 'Ajoutez une image',
                'row_attr' => [
                    'class' => 'flex flex-col m-4 w-4/5'
                ],
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'accept' => 'image/png, image/jpeg',
                ],
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png'
                        ],
                        'mimeTypesMessage' => 'Plese upload a valid JPEG/PNG image',
                    ])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

symfony/src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\LikedPost;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use App\Repository\CommentRepository;
use App\Repository\LikedPostRepository;
use App\Repository\PostRepository;
use App\Service\PostService;
use App\Service\UploaderService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/post')]
class PostController extends AbstractController
{
    #[Route('/', name: 'app_post_index')]
    public function index(PostService $postService): Response
    {
        $this->getUser() ? $currentUser = $this->getUser() : $currentUser = null;
        $posts = $postService->getPostsByDate(25, $currentUser);

        return $this->render('post/index.html.twig',
            [
                'controller_name' => 'PostController',
                'posts' => $posts
            ]);
    }

    #[Route('/new', name: 'app_post_new')]
    public function new(PostRepository $postRepository, Request $request, UploaderService $uploaderService): Response
    {
        if ($this->getUser() == null) {
            return $this->redirectToRoute('app_login');
        }

        $post = new Post();

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postFile = $form->get('imageFile')->getData();

            if ($postFile) {
                $filename = $uploaderService->uploadImage($postFile, UploaderService::POST);
                $post->setImage($filename);
            }

            $post->setUser($this->getUser());
            $postRepository->save($post, true);

            return $this->redirectToRoute('app_home');
        }

        return $this->render('post/new.html.twig',
            [
                'controller_name' => 'PostController',
                'post' => $post,
                'form' => $form
            ]);
    }

    #[Route('/{id}', name: 'app_post_show')]
    public function show(Post $post, Request $request, CommentRepository $commentRepository, PostService $postService): Response
    {
        $this->getUser() ? $currentUser = $this->getUser() : $currentUser = null;
        $data = $postService->RenderSinglePost($post, $currentUser);

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setUser($this->getUser())
                ->setPost($post);
            $commentRepository->save($comment, true);

            unset($comment);
            unset($form);
            $comment = new Comment();
            $form = $this->createForm(CommentType::class, $comment);

            $data = $postService->RenderSinglePost($post, $currentUser);
        }

        return $this->render('post/show.html.twig',
            [
                'controller_name' => 'PostController',
                'post' => $data[0],
                'form' => $form,
                'comment' => $comment,
                'comments' => $data[1]
            ]);
    }

    #[Route('/{id}/like', name: 'app_post_like')]
    public function like(Post $post, LikedPostRepository $likedPostRepository, Request $request): Response
    {
        $id = $post->getId();
        $redirect = $request->query->get('redirect');

        if ($this->getUser() == null) {
            return $this->redirectToRoute('app_login');
        }

        $likedPost = new LikedPost();

        if ($likedPostRepository->findOneBy(['post' => $post, 'user' => $this->getUser()])) {
            $this->redirectPost($redirect, $id);
        }

        $likedPost->setPost($post);
        $likedPost->setUser($this->getUser());
        $likedPostRepository->save($likedPost, true);

        return $this->redirectPost($redirect, $id);
    }

    #[Route('/{id}/dislike', name: 'app_post_dislike')]
    public function dislike(Post $post, LikedPostRepository $likedPostRepository, Request $request): Response
    {
        $id = $post->getId();
        $redirect = $request->query->get('redirect');

        if ($this->getUser() == null) {
            return $this->redirectToRoute('app_login');
        }

        if (!$likedPostRepository->findOneBy(['post' => $post, 'user' => $this->getUser()])) {
            $this->redirectPost($redirect, $id);
        }

        $likedPost = $likedPostRepository->findOneBy(['post' => $post, 'user' => $this->getUser()]);
        $likedPostRepository->remove($likedPost, true);
        return $this->redirectPost($redirect, $id);
    }

    #[Route('/{id}/remove', name: 'app_post_remove')]
    public function remove(PostRepository $postRepository, Post $post): Response
    {
        if ($post->getImage() !== null) {
            $filesystem = new Filesystem();
            $oldFile = $post->getImage();
            $path = $this->getParameter('post_img_directory') . '/' . $oldFile;
            $filesystem->remove($path);
        }

        $postRepository->remove($post, true);
        return $this->redirectToRoute('app_home');
    }

    private function redirectPost($redirect, $id): RedirectResponse
    {
        if ($redirect == 'post') {
            return $this->redirectToRoute('app_post_show', ['id' => $id]);
        } else {
            return $this->redirectToRoute('app_home');
        }
    }
}

symfony/templates/post/index.html.twig
    {% if app.user %}
        <a class="ml-20 m-5 py-2.5 px-5 bg-vert border-vert border-2 rounded-lg text-white transition duration-300 text-lg hover:bg-transparent hover:text-vert" href="{{ path('app_post_new') }}">Créer un post</a>
    {% endif %}

    {% for post in posts %}
        <article class=" mr-12 mb-12 ml-20 w-11/12  px-12 p-5 rounded-lg shadow-[0_0_80px_rgba(0,0,0,.07)]">
            <a class=" mx-12" href="{{ path('app_post_show', {'id': post.id}) }}">
                <h3 class="text-xl font-bold">{{post.title}}</h3>
                <p class="my-5">{{post.text}}</p>
                {% if post.image %}
                    <img class="h-52 my-3.5" src="{{ asset('uploads/post_img/' ~ post.image) }}" alt="">
                {% endif %}
                <div class="flex flew-row justify-between">       
                    <p class="text-lg"><span class="text-xs italic">Écrit par : </span>{{ post.user.username }}</p>
                    <p>{{post.createdAt|date('d/m/Y H:i', "Europe/Paris")}}</p>
                </div>
            </a>
            {% if app.user %}
                <div class="w-12 flex flex-row justify-around text-vert mb-5">
                    {% if post.isLiked %}
                        <a href="{{ path('app_post_dislike', {'id': post.id}) }}"><i class="fa-solid fa-heart"></i></a>
                    {% else %}
                        <a href="{{ path('app_post_like', {'id': post.id}) }}"><i class="fa-regular fa-heart"></i></a>
                    {% endif %}
                    <p>{{ post.likes }}</p>
                </div>
            {% else %}
                <div class="w-12 flex flex-row justify-around text-vert mb-5">
                    <a href="{{ path('app_login') }}"><i class="fa-regular fa-heart"></i></a>
                    <p>{{ post.likes|length }}</p>
                </div>
            {% endif %}
        </article>
    {% endfor %}

symfony/templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!{% endblock %}

{% block body %}
    <main  class=" mt-20 flex flex-col items-center justify-center font-Poppins">
        <h1 class="h1 text-vert">Créez un post</h1>
        {{ form_start(form, {'attr': {'class': 'flex flex-col items-center justify-center w-4/5'}}) }}
            {{ form_row(form.title, {'label_attr': {'class': 'mb-2'}, 'attr': {'class': 'py-2.5 px-5 bg-gris_input text-gris_text border-gris_input rounded-lg'}}, ) }}
            {{ form_row(form.text, {'label_attr': {'class': 'mb-2'}, 'attr': {'class': 'py-2.5 px-5 bg-gris_input text-gris_text border-gris_input rounded-lg'}}, ) }}
            {{ form_row(form.imageFile, {'label_attr': {'class': 'mb-2'}, 'attr': {'class': 'py-2.5 px-5 bg-gris_input text-gris_text border-gris_input rounded-lg'}}, ) }}
            <input class="m-5 py-2.5 px-5 bg-vert border-vert border-2 rounded-lg text-white transition duration-300 text-lg hover:bg-transparent hover:text-vert" type="submit" value="Poster"/>
        {{ form_end(form) }}
    </main>
{% endblock %}

symfony/templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PostController!{% endblock %}

{% block body %}
<main class="mt-5 ml-5 font-Poppins">
    <a class="m-5 text-vert transition duration-3000 decoration-2 hover:underline uppercase font-semibold" href="{{ path('app_home') }}"><i class="fa-solid fa-arrow-left"></i> Retour</a>
    <article class="m-12 px-12 p-5 rounded-lg shadow-[0_0_80px_rgba(0,0,0,.07)]">
        <h3 class="my-5 text-xl font-bold">{{post.title}}</h3>
        <p class="my-5">{{post.text}}</p>
        {% if post.image %}
            <img class="h-52 my-3.5" src="{{ asset('uploads/post_img/' ~ post.image) }}" alt="">
        {% endif %}
        <div class="flex flew-row justify-between">       
            <p class="text-lg"><span class="text-xs italic">Écrit par : </span>{{ post.user.username }}</p>
            <p>{{post.createdAt|date('d/m/Y H:i', "Europe/Paris")}}</p>
        </div>
        <div class="flex flex-row-reverse justify-between my-5">
            {% if app.user == post.user %}
                <a class="text-vert" href="{{ path('app_post_remove', {'id': post.id}) }}"><i class="fa-solid fa-trash"></i></a>
            {% endif %}
            {% if app.user %}
                <div class="w-12 flex flex-row justify-around text-vert ">
                    {% if post.isLiked %}
                        <a href="{{ path('app_post_dislike', {'id': post.id, 'redirect':'post'}) }}"><i class="fa-solid fa-heart"></i></a>
                    {% else %}
                        <a href="{{ path('app_post_like', {'id': post.id, 'redirect':'post'}) }}"><i class="fa-regular fa-heart"></i></a>
                    {% endif %}
                    <p>{{ post.likes }}</p>
                </div>
            {% else %}
                <div class="w-12 flex flex-row justify-around text-vert mb-5">
                    <a href="{{ path('app_login') }}"><i class="fa-regular fa-heart"></i></a>
                    <p>{{ post.likes|length }}</p>
                </div>
            {% endif %}
        </div>
    </article>
    <article>
        <section class="mx-12 my-14 ">
            <h3 class="my-5 text-xl font-bold">Commentaires</h3>
            {% if app.user %}
                {{ form_start(form) }}
                {{ form_errors(form.text) }}
                {{ form_widget(form.text, { 'attr': {'class': 'mx-12 w-2/4 py-2.5 px-5 bg-gris_input text-gris_text border-gris_input rounded-lg'}}, ) }}
                <input class="m-5 py-2.5 px-5 bg-vert border-vert border-2 rounded-lg text-white transition duration-300 text-mg hover:bg-transparent hover:text-vert" type="submit" value="Envoyer">
                {{ form_end(form)}}
            {% endif %}

            {# <h3>Commentaires • {{ comments|length }}</h3> #}
            {% if comments is empty %}
                Pas de commentaire...
            {% endif %}
            {% for comment in comments %}
                <article class=" mr-12 mb-12 ml-12">
                    <p class="my-6"><span class="font-semibold">{{ comment.user.username }}</span><br>{{ comment.text }}</p>
                    <div class=" flex flex-row justify-between">
                        <p>{{ comment.createdAt|date('d/m/y H:i', "Europe/Paris") }}</p>
                        {% if app.user %}
                            <div class="w-20 flex flex-row justify-between text-vert ">
                                <div class="w-12 flex flex-row justify-around">
                                    {% if comment.isLiked %}
                                        <a href="{{ path('app_comment_dislike', {'id': comment.id, 'post': post.id}) }}"><i class="fa-solid fa-heart"></i></a>
                                    {% else %}
                                        <a href="{{ path('app_comment_like', {'id': comment.id, 'post': post.id}) }}"><i class="fa-regular fa-heart"></i></a>
                                    {% endif %}
                                    <p>{{ comment.likes }}</p>
                                </div>                    
                                {% if app.user == comment.user %}
                                    <a class="text-vert" href="{{ path('app_comment_remove', {'id': comment.id, 'post': post.id}) }}"><i class="fa-solid fa-trash"></i></a>
                                {% endif %}
                            </div>
                        {% else %}
                            <div class="w-12 flex flex-row justify-around text-vert mb-5">
                                <a href="{{ path('app_login') }}"><i class="fa-regular fa-heart"></i></a>
                                <p>{{ comment.likes|length }}</p>

                            </div>
                        {% endif %}
                    </div>
                </article>
            {% endfor %}
        </section>
    </article>
</main>
{% endblock %}